"""Agregar columna juego

Revision ID: 657c1cb2b58c
Revises: 
Create Date: 2025-11-12 18:09:36.269827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657c1cb2b58c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('juego', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('juego')

    # ### end Alembic commands ###
