"""Add director and jugadores to dashboard

Revision ID: 67a2188fc5f9
Revises: 657c1cb2b58c
Create Date: 2025-11-18 13:35:45.066721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a2188fc5f9'
down_revision = '657c1cb2b58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jugadores', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('jugadores')
        batch_op.drop_column('director')

    # ### end Alembic commands ###
